-- Demo content for Artificial Home (generated by scripts/generate-seed.ts).
-- Run AFTER all files in supabase/migrations (0001 – 0004).
-- It clears the shop content first. Orders, messages, subscribers and admins are untouched.
begin;
truncate public.site_settings, public.profile, public.banners, public.faqs, public.testimonials, public.blog_posts;
delete from public.products;
delete from public.categories;

insert into public.site_settings (website_name, logo_url, accent_color, accent_color_2, default_theme, contact_email, public_phone, seo_title, seo_description, footer_text, hire_label, sections, announcement, whatsapp_number, delivery_inside, delivery_outside, free_delivery_min, delivery_note, order_prefix, cod_enabled, bkash_number, nagad_number, rocket_number, payment_qr_url, payment_note, promo_kicker, promo_title, promo_text, promo_button, promo_link, promo_image_url, promo_ends_at, gallery_images, map_embed_url, cursor_enabled) values
  ('Artificial Home', null, '#e0457b', '#c9956b', 'light', 'hello@artificialhome.demo', '+880 1712-345678', 'Artificial Home — Artificial Jewellery & Accessories in Bangladesh', 'Shop trendy artificial jewellery, bangles, earrings, necklaces, hair clips and beauty care. Cash on Delivery and bKash, Nagad, Rocket all over Bangladesh.', 'Trendy artificial jewellery, hair accessories and beauty care — made for every girl, delivered all over Bangladesh.', 'Shop Now', '[]'::jsonb, 'Free delivery on orders over ৳2,000 · Cash on Delivery all over Bangladesh', '8801712345678', 60, 120, 2000, 'Inside Dhaka: 1–2 days · Outside Dhaka: 2–4 days', 'AH', true, '01712-345678', '01812-345678', '01912-3456789', '/demo/payment-qr.svg', 'Use Send Money for the total amount, then enter the number you paid from and the Transaction ID.', 'Limited time offer', 'Festive Sale — Up to 40% Off', 'Bridal sets, jhumkas, bangles and more. New designs added every week.', 'Shop the Sale', '/shop?sale=1', '/demo/promo.svg', '2026-12-31T17:59:00.000Z', '["/demo/products/gold-jhumka-earrings-1.svg","/demo/products/pearl-hair-clip-set-1.svg","/demo/products/bridal-choker-necklace-1.svg","/demo/products/golden-kundan-churi-set-1.svg","/demo/products/rose-glow-face-cream-1.svg","/demo/products/rose-gold-charm-bracelet-1.svg"]'::jsonb, 'https://www.openstreetmap.org/export/embed.html?bbox=90.3866%2C23.7837%2C90.4266%2C23.8037&layer=mapnik&marker=23.7937%2C90.4066', true);

insert into public.profile (full_name, professional_title, short_intro, bio, email, phone, location, profile_image_url, about_image_url, social_links) values
  ('Sumaiya Rahman', 'Founder, Artificial Home', 'From a small Facebook page to thousands of happy customers all over Bangladesh.', 'Artificial Home started in 2021 as a tiny Facebook page run from my bedroom in Dhaka. I loved jewellery but good designs were either too expensive or hard to find, so I started sourcing pieces I would wear myself.

Today we pack hundreds of orders every week — bangles, jhumkas, bridal sets, hair clips and gentle beauty care. Every piece is checked by hand before it leaves our studio, and we still read every message ourselves.

Thank you for being part of our story. We hope you find something that makes you smile.', 'hello@artificialhome.demo', '+880 1712-345678', 'Road 11, Banani, Dhaka', '/demo/avatar-owner.svg', '/demo/about-studio.svg', '[{"platform":"facebook","url":"https://facebook.com/"},{"platform":"instagram","url":"https://instagram.com/"},{"platform":"tiktok","url":"https://tiktok.com/"},{"platform":"youtube","url":"https://youtube.com/"},{"platform":"whatsapp","url":"https://wa.me/8801712345678"}]'::jsonb);

insert into public.categories (name, slug, description, image_url, active, sort_order) values
  ('Bangles', 'bangles', 'Churi and kada for every outfit and occasion.', '/demo/cat-bangles.svg', true, 1),
  ('Earrings', 'earrings', 'Jhumka, chandbali, studs and pearl drops.', '/demo/cat-earrings.svg', true, 2),
  ('Necklaces', 'necklaces', 'Chokers, pendants and layered pearls.', '/demo/cat-necklaces.svg', true, 3),
  ('Jewellery Sets', 'jewellery-sets', 'Matching goina sets for weddings and parties.', '/demo/cat-jewellery-sets.svg', true, 4),
  ('Bracelets', 'bracelets', 'Charm, pearl and crystal bracelets.', '/demo/cat-bracelets.svg', true, 5),
  ('Hair Accessories', 'hair-accessories', 'Clips, claw clips, tikli and scrunchies.', '/demo/cat-hair-accessories.svg', true, 6),
  ('Beauty Care', 'beauty-care', 'Gentle creams, lipsticks and skin care.', '/demo/cat-beauty-care.svg', true, 7);

insert into public.products (name, slug, category_slug, short_description, description, price, sale_price, images, colors, stock, sku, badge, featured, is_new, rating, review_count, status, sort_order) values
  ('Golden Kundan Churi Set', 'golden-kundan-churi-set', 'bangles', 'Set of 4 kundan bangles with ruby and emerald stones.', 'Set of 4 kundan bangles with ruby and emerald stones.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 1450, 1150, '["/demo/products/golden-kundan-churi-set-1.svg","/demo/products/golden-kundan-churi-set-2.svg"]'::jsonb, '[{"name":"Gold","hex":"#d4a24c"},{"name":"Rose Gold","hex":"#d9a08b"}]'::jsonb, 24, 'AH-001', 'Bestseller', true, false, 4.9, 128, 'published', 1),
  ('Pearl Glass Churi', 'pearl-glass-churi', 'bangles', 'Shiny glass churi with a soft pearl finish, set of 12.', 'Shiny glass churi with a soft pearl finish, set of 12.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 650, null, '["/demo/products/pearl-glass-churi-1.svg","/demo/products/pearl-glass-churi-2.svg"]'::jsonb, '[{"name":"Pearl White","hex":"#f4efe6"},{"name":"Pink","hex":"#f28ab2"}]'::jsonb, 40, 'AH-002', null, false, true, 4.7, 54, 'published', 2),
  ('Maroon Velvet Churi', 'maroon-velvet-churi', 'bangles', 'Velvet-wrapped bangles with golden stone work.', 'Velvet-wrapped bangles with golden stone work.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 890, 750, '["/demo/products/maroon-velvet-churi-1.svg","/demo/products/maroon-velvet-churi-2.svg"]'::jsonb, '[{"name":"Maroon","hex":"#7a1f35"},{"name":"Red","hex":"#c8203d"}]'::jsonb, 18, 'AH-003', 'Sale', false, false, 4.8, 61, 'published', 3),
  ('Oxidised Silver Kada', 'oxidised-silver-kada', 'bangles', 'Boho oxidised kada with a floral pattern.', 'Boho oxidised kada with a floral pattern.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 780, null, '["/demo/products/oxidised-silver-kada-1.svg","/demo/products/oxidised-silver-kada-2.svg"]'::jsonb, '[{"name":"Silver","hex":"#c0c4cc"}]'::jsonb, 15, 'AH-004', null, false, false, 4.6, 33, 'published', 4),
  ('Gold Jhumka Earrings', 'gold-jhumka-earrings', 'earrings', 'Classic bell jhumka with pearl drops.', 'Classic bell jhumka with pearl drops.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 850, 690, '["/demo/products/gold-jhumka-earrings-1.svg","/demo/products/gold-jhumka-earrings-2.svg"]'::jsonb, '[{"name":"Gold","hex":"#d4a24c"},{"name":"Rose Gold","hex":"#d9a08b"}]'::jsonb, 36, 'AH-005', 'Bestseller', true, false, 4.9, 212, 'published', 5),
  ('Pearl Drop Earrings', 'pearl-drop-earrings', 'earrings', 'Elegant single pearl drops for office and parties.', 'Elegant single pearl drops for office and parties.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 590, null, '["/demo/products/pearl-drop-earrings-1.svg","/demo/products/pearl-drop-earrings-2.svg"]'::jsonb, '[{"name":"Pearl White","hex":"#f4efe6"},{"name":"Gold","hex":"#d4a24c"}]'::jsonb, 30, 'AH-006', 'New', false, true, 4.8, 47, 'published', 6),
  ('Chandbali Earrings', 'chandbali-earrings', 'earrings', 'Half-moon chandbali with emerald stones.', 'Half-moon chandbali with emerald stones.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 1150, 950, '["/demo/products/chandbali-earrings-1.svg","/demo/products/chandbali-earrings-2.svg"]'::jsonb, '[{"name":"Gold","hex":"#d4a24c"},{"name":"Emerald","hex":"#1f7a5a"}]'::jsonb, 12, 'AH-007', 'Sale', true, false, 4.8, 88, 'published', 7),
  ('Tiny Stud Earring Set', 'tiny-stud-earring-set', 'earrings', 'Six pairs of tiny studs for everyday wear.', 'Six pairs of tiny studs for everyday wear.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 450, null, '["/demo/products/tiny-stud-earring-set-1.svg","/demo/products/tiny-stud-earring-set-2.svg"]'::jsonb, '[{"name":"Silver","hex":"#c0c4cc"},{"name":"Gold","hex":"#d4a24c"}]'::jsonb, 50, 'AH-008', null, false, false, 4.7, 76, 'published', 8),
  ('Bridal Choker Necklace', 'bridal-choker-necklace', 'necklaces', 'Kundan bridal choker with matching earrings.', 'Kundan bridal choker with matching earrings.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 2850, 2350, '["/demo/products/bridal-choker-necklace-1.svg","/demo/products/bridal-choker-necklace-2.svg"]'::jsonb, '[{"name":"Gold","hex":"#d4a24c"},{"name":"Red","hex":"#c8203d"}]'::jsonb, 9, 'AH-009', 'Bestseller', true, false, 5, 64, 'published', 9),
  ('Layered Pearl Necklace', 'layered-pearl-necklace', 'necklaces', 'Three layers of soft pearls on a golden chain.', 'Three layers of soft pearls on a golden chain.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 1350, null, '["/demo/products/layered-pearl-necklace-1.svg","/demo/products/layered-pearl-necklace-2.svg"]'::jsonb, '[{"name":"Pearl White","hex":"#f4efe6"}]'::jsonb, 20, 'AH-010', 'New', false, true, 4.8, 39, 'published', 10),
  ('Minimal Heart Pendant', 'minimal-heart-pendant', 'necklaces', 'Dainty heart pendant on a fine chain.', 'Dainty heart pendant on a fine chain.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 690, 590, '["/demo/products/minimal-heart-pendant-1.svg","/demo/products/minimal-heart-pendant-2.svg"]'::jsonb, '[{"name":"Rose Gold","hex":"#d9a08b"},{"name":"Gold","hex":"#d4a24c"},{"name":"Silver","hex":"#c0c4cc"}]'::jsonb, 45, 'AH-011', null, false, false, 4.7, 102, 'published', 11),
  ('Temple Coin Necklace', 'temple-coin-necklace', 'necklaces', 'Traditional coin necklace with antique finish.', 'Traditional coin necklace with antique finish.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 1950, null, '["/demo/products/temple-coin-necklace-1.svg","/demo/products/temple-coin-necklace-2.svg"]'::jsonb, '[{"name":"Gold","hex":"#d4a24c"}]'::jsonb, 8, 'AH-012', null, false, false, 4.8, 29, 'published', 12),
  ('Bridal Goina Set', 'bridal-goina-set', 'jewellery-sets', 'Necklace, jhumka and tikli — the full bridal look.', 'Necklace, jhumka and tikli — the full bridal look.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 4950, 3990, '["/demo/products/bridal-goina-set-1.svg","/demo/products/bridal-goina-set-2.svg"]'::jsonb, '[{"name":"Gold","hex":"#d4a24c"},{"name":"Maroon","hex":"#7a1f35"}]'::jsonb, 6, 'AH-013', 'Bestseller', true, false, 5, 41, 'published', 13),
  ('Party Wear Necklace Set', 'party-wear-necklace-set', 'jewellery-sets', 'Crystal necklace with matching studs.', 'Crystal necklace with matching studs.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 2450, 1990, '["/demo/products/party-wear-necklace-set-1.svg","/demo/products/party-wear-necklace-set-2.svg"]'::jsonb, '[{"name":"Silver","hex":"#c0c4cc"},{"name":"Lilac","hex":"#b99ad8"}]'::jsonb, 14, 'AH-014', 'New', true, true, 4.8, 36, 'published', 14),
  ('Everyday Pearl Set', 'everyday-pearl-set', 'jewellery-sets', 'Light pearl necklace and earrings for daily wear.', 'Light pearl necklace and earrings for daily wear.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 1690, null, '["/demo/products/everyday-pearl-set-1.svg","/demo/products/everyday-pearl-set-2.svg"]'::jsonb, '[{"name":"Pearl White","hex":"#f4efe6"},{"name":"Rose Gold","hex":"#d9a08b"}]'::jsonb, 22, 'AH-015', null, false, false, 4.7, 45, 'published', 15),
  ('Rose Gold Charm Bracelet', 'rose-gold-charm-bracelet', 'bracelets', 'Charm bracelet with heart, star and moon.', 'Charm bracelet with heart, star and moon.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 950, 790, '["/demo/products/rose-gold-charm-bracelet-1.svg","/demo/products/rose-gold-charm-bracelet-2.svg"]'::jsonb, '[{"name":"Rose Gold","hex":"#d9a08b"},{"name":"Gold","hex":"#d4a24c"}]'::jsonb, 28, 'AH-016', 'Sale', true, false, 4.8, 73, 'published', 16),
  ('Pearl Beaded Bracelet', 'pearl-beaded-bracelet', 'bracelets', 'Stretchable pearl bracelet, one size fits all.', 'Stretchable pearl bracelet, one size fits all.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 550, null, '["/demo/products/pearl-beaded-bracelet-1.svg","/demo/products/pearl-beaded-bracelet-2.svg"]'::jsonb, '[{"name":"Pearl White","hex":"#f4efe6"},{"name":"Pink","hex":"#f28ab2"}]'::jsonb, 35, 'AH-017', 'New', false, true, 4.7, 38, 'published', 17),
  ('Crystal Tennis Bracelet', 'crystal-tennis-bracelet', 'bracelets', 'Sparkling crystal line bracelet for evenings.', 'Sparkling crystal line bracelet for evenings.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 1250, 990, '["/demo/products/crystal-tennis-bracelet-1.svg","/demo/products/crystal-tennis-bracelet-2.svg"]'::jsonb, '[{"name":"Silver","hex":"#c0c4cc"},{"name":"Rose Gold","hex":"#d9a08b"}]'::jsonb, 16, 'AH-018', null, false, false, 4.8, 52, 'published', 18),
  ('Pearl Hair Clip Set', 'pearl-hair-clip-set', 'hair-accessories', 'Set of 6 pearl hair clips in different sizes.', 'Set of 6 pearl hair clips in different sizes.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 390, 320, '["/demo/products/pearl-hair-clip-set-1.svg","/demo/products/pearl-hair-clip-set-2.svg"]'::jsonb, '[{"name":"Pearl White","hex":"#f4efe6"},{"name":"Gold","hex":"#d4a24c"}]'::jsonb, 60, 'AH-019', 'Bestseller', true, true, 4.9, 184, 'published', 19),
  ('Butterfly Claw Clips', 'butterfly-claw-clips', 'hair-accessories', 'Pack of 3 matte butterfly claw clips.', 'Pack of 3 matte butterfly claw clips.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 350, null, '["/demo/products/butterfly-claw-clips-1.svg","/demo/products/butterfly-claw-clips-2.svg"]'::jsonb, '[{"name":"Pink","hex":"#f28ab2"},{"name":"Lilac","hex":"#b99ad8"},{"name":"Black","hex":"#222222"}]'::jsonb, 55, 'AH-020', 'New', false, true, 4.7, 97, 'published', 20),
  ('Floral Bridal Tikli', 'floral-bridal-tikli', 'hair-accessories', 'Maang tikka with a floral kundan centre.', 'Maang tikka with a floral kundan centre.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 750, 650, '["/demo/products/floral-bridal-tikli-1.svg","/demo/products/floral-bridal-tikli-2.svg"]'::jsonb, '[{"name":"Gold","hex":"#d4a24c"},{"name":"Red","hex":"#c8203d"}]'::jsonb, 20, 'AH-021', null, false, false, 4.8, 44, 'published', 21),
  ('Satin Scrunchie Pack', 'satin-scrunchie-pack', 'hair-accessories', 'Pack of 5 soft satin scrunchies.', 'Pack of 5 soft satin scrunchies.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 290, null, '["/demo/products/satin-scrunchie-pack-1.svg","/demo/products/satin-scrunchie-pack-2.svg"]'::jsonb, '[{"name":"Pink","hex":"#f28ab2"},{"name":"Maroon","hex":"#7a1f35"},{"name":"Black","hex":"#222222"}]'::jsonb, 80, 'AH-022', null, false, false, 4.6, 58, 'published', 22),
  ('Rose Glow Face Cream', 'rose-glow-face-cream', 'beauty-care', 'Light day cream with rose water and vitamin E.', 'Light day cream with rose water and vitamin E.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 650, 550, '["/demo/products/rose-glow-face-cream-1.svg","/demo/products/rose-glow-face-cream-2.svg"]'::jsonb, '[]'::jsonb, 40, 'AH-023', 'Bestseller', true, false, 4.8, 156, 'published', 23),
  ('Velvet Matte Lipstick', 'velvet-matte-lipstick', 'beauty-care', 'Long-lasting matte lipstick, soft on the lips.', 'Long-lasting matte lipstick, soft on the lips.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 450, null, '["/demo/products/velvet-matte-lipstick-1.svg","/demo/products/velvet-matte-lipstick-2.svg"]'::jsonb, '[{"name":"Red","hex":"#c8203d"},{"name":"Nude","hex":"#c98f7a"},{"name":"Pink","hex":"#f28ab2"},{"name":"Maroon","hex":"#7a1f35"}]'::jsonb, 70, 'AH-024', 'New', false, true, 4.7, 91, 'published', 24),
  ('Aloe Vera Night Gel', 'aloe-vera-night-gel', 'beauty-care', 'Soothing aloe night gel for all skin types.', 'Soothing aloe night gel for all skin types.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 390, null, '["/demo/products/aloe-vera-night-gel-1.svg","/demo/products/aloe-vera-night-gel-2.svg"]'::jsonb, '[]'::jsonb, 45, 'AH-025', null, false, false, 4.6, 67, 'published', 25);

insert into public.banners (kicker, title, subtitle, button_label, button_link, image_url, active, sort_order) values
  ('New Bridal Collection', 'Shine Brighter on Your Special Day', 'Handpicked kundan sets, jhumkas and tikli — made to make every moment golden.', 'Shop Bridal', '/shop/jewellery-sets', '/demo/banner-bridal.svg', true, 1),
  ('Festive Sale · Up to 40% Off', 'Jhumkas & Bangles You''ll Love', 'Trending designs for Eid, weddings and every party this season.', 'Shop the Sale', '/shop?sale=1', '/demo/banner-sale.svg', true, 2),
  ('Everyday Pearls', 'Little Details, Big Smiles', 'Pearl clips, dainty chains and studs for college, office and brunch.', 'Explore New In', '/shop?new=1', '/demo/banner-pearls.svg', true, 3);

insert into public.testimonials (name, role, company, project_title, quote, avatar_url, rating, active, sort_order) values
  ('Nusrat Jahan', 'Dhaka', null, 'Bridal Goina Set', 'I wore the bridal set on my holud and everyone asked where I got it! It looks exactly like the pictures and the packaging was so pretty.', '/demo/avatar-1.svg', 5, true, 1),
  ('Tasnim Akter', 'Chattogram', null, 'Gold Jhumka Earrings', 'Delivery to Chattogram took just 2 days. The jhumkas are light and don''t hurt my ears even after a full day.', '/demo/avatar-2.svg', 5, true, 2),
  ('Sadia Islam', 'Sylhet', null, 'Pearl Hair Clip Set', 'Ordered with bKash and they confirmed on WhatsApp within minutes. The pearl clips are my new favourite for college.', '/demo/avatar-3.svg', 5, true, 3),
  ('Farzana Rahman', 'Rajshahi', null, 'Rose Glow Face Cream', 'The rose cream is so light and smells lovely. My skin feels soft all day. Already ordered my second jar!', '/demo/avatar-4.svg', 4, true, 4);

insert into public.faqs (question, answer, active, sort_order) values
  ('How do I place an order?', 'Add products to your cart, go to Checkout, fill in your name, phone and address, choose a payment method and press Place Order. You can also order on WhatsApp.', true, 1),
  ('What are the delivery charges?', 'Inside Dhaka ৳60 and outside Dhaka ৳120. Orders over ৳2,000 get free delivery.', true, 2),
  ('How long does delivery take?', 'Inside Dhaka 1–2 working days, outside Dhaka 2–4 working days. We call you before sending the parcel.', true, 3),
  ('Which payment methods do you accept?', 'Cash on Delivery all over Bangladesh, plus bKash, Nagad, Rocket and Bangla QR. For mobile payments, send the total and enter your Transaction ID at checkout.', true, 4),
  ('Can I return or exchange a product?', 'Yes. If a product arrives damaged or different from the picture, tell us within 3 days with a photo and we will exchange it for free.', true, 5),
  ('Is the jewellery safe for sensitive skin?', 'Our pieces use skin-friendly, nickel-free plating. Keep them away from water and perfume to keep the shine for longer.', true, 6);

insert into public.blog_posts (title, slug, excerpt, content, cover_image_url, category, read_time, published_at, status) values
  ('How to Keep Your Artificial Jewellery Shining for Years', 'care-for-artificial-jewellery', 'Five simple habits that keep your favourite pieces looking brand new.', 'Artificial jewellery can last for years with a little care. These habits make the biggest difference.

## 1. Put it on last
Wear your jewellery after perfume, lotion and hairspray, not before.

## 2. Keep it dry
Take it off before a shower, a swim or washing your hands.

## 3. Wipe after wearing
A soft, dry cloth removes sweat and oil that make plating dull.

## 4. Store pieces separately
Use the zip pouch or a soft box so pieces don''t scratch each other.

## 5. Add silica gel
A small silica packet in your jewellery box keeps moisture away.', '/demo/blog-care.svg', 'Jewellery Care', '3 min read', '2026-09-20', 'published'),
  ('5 Jewellery Trends Every Girl Will Love This Season', 'jewellery-trends-this-season', 'From oversized jhumkas to pearl hair clips — here is what everyone is wearing.', 'This season is all about mixing traditional and modern.

## Oversized jhumkas
Big bells with pearl drops look amazing with both saree and kurti.

## Pearl everything
Pearl clips, pearl bracelets and layered pearl necklaces are everywhere.

## Stacked bangles
Mix velvet, glass and metal churi in two or three colours.

## Dainty pendants
A tiny heart or initial pendant is perfect for college and office.

## Claw clips
Matte butterfly claw clips are the easiest way to look put-together in seconds.', '/demo/blog-trends.svg', 'Style Guide', '4 min read', '2026-09-05', 'published'),
  ('Choosing Earrings for Your Face Shape', 'earrings-for-your-face-shape', 'A quick guide to finding earrings that flatter you the most.', 'The right earrings can brighten your whole look. Here is a simple guide.

## Round face
Long drops and chandbalis add length.

## Oval face
Lucky you — almost everything works, from studs to big jhumkas.

## Square face
Round hoops and soft pearl drops soften strong angles.

## Heart face
Earrings that are wider at the bottom, like jhumkas, balance a narrow chin.', '/demo/blog-earrings.svg', 'Style Guide', '3 min read', '2026-08-18', 'published');

commit;

-- ------------------------------------------------------------------
-- Make your dashboard owner (run once, after creating the user in
-- Supabase -> Authentication -> Users). Replace the email below.
-- ------------------------------------------------------------------
-- insert into public.admins (user_id, display_name)
-- select id, 'Shop Owner' from auth.users where email = 'owner@example.com'
-- on conflict (user_id) do update set active = true;
