-- =====================================================================
-- Website installed into schema "site05" (generated by scripts/build-schema-sql.mjs).
-- Storage bucket: "site05-media".
-- WARNING: run this file ONCE. Running it again replaces all website content with the demo content
-- (messages and admins are kept).
--
-- AFTER running this file:
--   1. Project Settings → Data API → "Exposed schemas": add site05  (then Save)
--   2. Website .env: NEXT_PUBLIC_SUPABASE_SCHEMA=site05
--   3. Make your owner an admin of this website (bottom of this file).
-- =====================================================================

create schema if not exists site05;
grant usage on schema site05 to anon, authenticated, service_role;
alter default privileges in schema site05 grant all on tables to anon, authenticated, service_role;
alter default privileges in schema site05 grant all on sequences to anon, authenticated, service_role;
alter default privileges in schema site05 grant execute on functions to anon, authenticated, service_role;
-- Row Level Security (enabled on every table below) still decides who can read or write.

-- >>> 0001_init.sql
-- =====================================================================
-- Business Portfolio — initial schema
-- Single-owner portfolio. Public can read published/active content;
-- only users listed in site05.admins (and active) can write.
-- =====================================================================


-- ---------- helpers ----------
create or replace function site05.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

-- ---------- admins (dashboard users) ----------
create table if not exists site05.admins (
  user_id uuid primary key references auth.users (id) on delete cascade,
  display_name text not null default 'Owner',
  avatar_url text,
  role text not null default 'owner' check (role in ('owner')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function site05.is_admin()
returns boolean
language sql stable security definer set search_path = site05
as $$
  select exists (
    select 1 from site05.admins a where a.user_id = auth.uid() and a.active
  );
$$;
revoke all on function site05.is_admin() from public;
grant execute on function site05.is_admin() to anon, authenticated;

-- ---------- site settings (single row) ----------
create table if not exists site05.site_settings (
  id uuid primary key default gen_random_uuid(),
  website_name text not null,
  logo_url text,
  accent_color text not null default '#ff014f' check (accent_color ~* '^#([0-9a-f]{3}|[0-9a-f]{6})$'),
  default_theme text not null default 'dark' check (default_theme in ('dark', 'light', 'system')),
  contact_email text not null,
  public_phone text,
  seo_title text not null,
  seo_description text not null,
  footer_text text not null default '',
  hire_label text not null default 'Hire Me',
  updated_at timestamptz not null default now()
);

-- ---------- profile (single row) ----------
create table if not exists site05.profile (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  professional_title text not null,
  typed_roles text[] not null default '{}',
  short_intro text not null default '',
  bio text not null default '',
  email text not null,
  phone text,
  location text not null default '',
  profile_image_url text not null,
  hero_image_url text,
  resume_url text,
  availability_status text not null default '',
  social_links jsonb not null default '[]'::jsonb,
  skill_tools jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------- content tables ----------
create table if not exists site05.services (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  short_description text not null,
  icon_key text,
  active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists site05.projects (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  slug text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  category text not null,
  year int not null,
  client text,
  role text,
  intro text not null,
  challenge text,
  solution text,
  result text,
  cover_image_url text not null,
  gallery jsonb not null default '[]'::jsonb,
  live_url text,
  likes int not null default 0,
  featured boolean not null default false,
  status text not null default 'published' check (status in ('published', 'draft')),
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists site05.resume_items (
  id uuid primary key default gen_random_uuid(),
  type text not null check (type in ('education', 'experience')),
  title text not null,
  subtitle text not null,
  period text not null,
  badge text,
  description text not null default '',
  active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists site05.skills (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  category text not null,
  level int not null default 80 check (level between 0 and 100),
  active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists site05.testimonials (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  role text,
  company text,
  project_title text,
  quote text not null,
  avatar_url text,
  rating int not null default 5 check (rating between 1 and 5),
  active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists site05.clients (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  category text not null default 'Brand',
  logo_url text,
  website_url text,
  active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists site05.pricing_plans (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  tagline text not null default '',
  price text not null,
  period text not null default '',
  description text not null default '',
  features text[] not null default '{}',
  cta_label text not null default 'Order Now',
  highlighted boolean not null default false,
  active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists site05.blog_posts (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  slug text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  excerpt text not null,
  content text not null,
  cover_image_url text not null,
  category text not null,
  read_time text not null default '3 min read',
  published_at date not null default current_date,
  status text not null default 'published' check (status in ('published', 'draft')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists site05.messages (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 2 and 80),
  email text not null check (char_length(email) between 5 and 120),
  phone text check (phone is null or char_length(phone) <= 30),
  service text check (service is null or char_length(service) <= 80),
  budget text check (budget is null or char_length(budget) <= 40),
  message text not null check (char_length(message) between 10 and 4000),
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

-- ---------- updated_at triggers ----------
do $$
declare t text;
begin
  foreach t in array array['admins','site_settings','profile','services','projects','resume_items','skills','testimonials','clients','pricing_plans','blog_posts']
  loop
    execute format('drop trigger if exists trg_%1$s_updated on site05.%1$s', t);
    execute format('create trigger trg_%1$s_updated before update on site05.%1$s for each row execute function site05.set_updated_at()', t);
  end loop;
end $$;

-- ---------- Row Level Security ----------
alter table site05.admins enable row level security;
alter table site05.site_settings enable row level security;
alter table site05.profile enable row level security;
alter table site05.services enable row level security;
alter table site05.projects enable row level security;
alter table site05.resume_items enable row level security;
alter table site05.skills enable row level security;
alter table site05.testimonials enable row level security;
alter table site05.clients enable row level security;
alter table site05.pricing_plans enable row level security;
alter table site05.blog_posts enable row level security;
alter table site05.messages enable row level security;

-- admins: a user can read and update only their own row (never role/active via app)
drop policy if exists "admins read self" on site05.admins;
create policy "admins read self" on site05.admins for select to authenticated using (user_id = auth.uid());
drop policy if exists "admins update self" on site05.admins;
create policy "admins update self" on site05.admins for update to authenticated
  using (user_id = auth.uid() and site05.is_admin())
  with check (user_id = auth.uid() and role = 'owner' and active = true);

-- public read policies
drop policy if exists "public read settings" on site05.site_settings;
create policy "public read settings" on site05.site_settings for select using (true);
drop policy if exists "public read profile" on site05.profile;
create policy "public read profile" on site05.profile for select using (true);
drop policy if exists "public read services" on site05.services;
create policy "public read services" on site05.services for select using (active or site05.is_admin());
drop policy if exists "public read projects" on site05.projects;
create policy "public read projects" on site05.projects for select using (status = 'published' or site05.is_admin());
drop policy if exists "public read resume" on site05.resume_items;
create policy "public read resume" on site05.resume_items for select using (active or site05.is_admin());
drop policy if exists "public read skills" on site05.skills;
create policy "public read skills" on site05.skills for select using (active or site05.is_admin());
drop policy if exists "public read testimonials" on site05.testimonials;
create policy "public read testimonials" on site05.testimonials for select using (active or site05.is_admin());
drop policy if exists "public read clients" on site05.clients;
create policy "public read clients" on site05.clients for select using (active or site05.is_admin());
drop policy if exists "public read pricing" on site05.pricing_plans;
create policy "public read pricing" on site05.pricing_plans for select using (active or site05.is_admin());
drop policy if exists "public read posts" on site05.blog_posts;
create policy "public read posts" on site05.blog_posts for select using (status = 'published' or site05.is_admin());

-- admin write policies
do $$
declare t text;
begin
  foreach t in array array['site_settings','profile','services','projects','resume_items','skills','testimonials','clients','pricing_plans','blog_posts']
  loop
    execute format('drop policy if exists "admin insert %1$s" on site05.%1$s', t);
    execute format('create policy "admin insert %1$s" on site05.%1$s for insert to authenticated with check (site05.is_admin())', t);
    execute format('drop policy if exists "admin update %1$s" on site05.%1$s', t);
    execute format('create policy "admin update %1$s" on site05.%1$s for update to authenticated using (site05.is_admin()) with check (site05.is_admin())', t);
    execute format('drop policy if exists "admin delete %1$s" on site05.%1$s', t);
    execute format('create policy "admin delete %1$s" on site05.%1$s for delete to authenticated using (site05.is_admin())', t);
  end loop;
end $$;

-- messages: anyone may submit (validated by CHECK constraints); only admins can read/manage
drop policy if exists "anyone can send message" on site05.messages;
create policy "anyone can send message" on site05.messages for insert to anon, authenticated with check (is_read = false);
drop policy if exists "admin read messages" on site05.messages;
create policy "admin read messages" on site05.messages for select to authenticated using (site05.is_admin());
drop policy if exists "admin update messages" on site05.messages;
create policy "admin update messages" on site05.messages for update to authenticated using (site05.is_admin()) with check (site05.is_admin());
drop policy if exists "admin delete messages" on site05.messages;
create policy "admin delete messages" on site05.messages for delete to authenticated using (site05.is_admin());

-- ---------- Storage ----------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'site05-media',
  'site05-media',
  true,
  5242880, -- 5 MB
  array['image/jpeg', 'image/png', 'image/webp', 'image/avif', 'application/pdf']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "public read media [site05]" on storage.objects;
create policy "public read media [site05]" on storage.objects for select using (bucket_id = 'site05-media');
drop policy if exists "admin upload media [site05]" on storage.objects;
create policy "admin upload media [site05]" on storage.objects for insert to authenticated
  with check (bucket_id = 'site05-media' and site05.is_admin()
    and (storage.foldername(name))[1] in ('profile', 'projects', 'services', 'testimonials', 'clients', 'blog', 'documents', 'settings'));
drop policy if exists "admin update media [site05]" on storage.objects;
create policy "admin update media [site05]" on storage.objects for update to authenticated
  using (bucket_id = 'site05-media' and site05.is_admin());
drop policy if exists "admin delete media [site05]" on storage.objects;
create policy "admin delete media [site05]" on storage.objects for delete to authenticated
  using (bucket_id = 'site05-media' and site05.is_admin());


-- >>> 0002_hardening.sql
-- =====================================================================
-- Security hardening (run after 0001_init.sql). Safe to re-run.
-- =====================================================================

-- ---------- Contact form: database-level anti-spam ----------
-- The anon key is public, so someone could call the REST API directly and
-- skip the website's rate limit. This trigger caps volume in the database.
create or replace function site05.messages_guard()
returns trigger
language plpgsql security definer set search_path = site05
as $$
begin
  -- Clients can never set these themselves.
  new.is_read := false;
  new.created_at := now();

  if (select count(*) from site05.messages where created_at > now() - interval '10 minutes') >= 30 then
    raise exception 'Too many messages right now. Please try again later.' using errcode = 'P0001';
  end if;

  if (select count(*) from site05.messages
      where lower(email) = lower(new.email) and created_at > now() - interval '1 hour') >= 3 then
    raise exception 'Too many messages from this email. Please try again later.' using errcode = 'P0001';
  end if;

  if new.email !~* '^[^@\s]+@[^@\s]+\.[^@\s]+$' then
    raise exception 'Invalid email.' using errcode = 'P0001';
  end if;

  return new;
end $$;

drop trigger if exists trg_messages_guard on site05.messages;
create trigger trg_messages_guard before insert on site05.messages
for each row execute function site05.messages_guard();

create index if not exists messages_created_at_idx on site05.messages (created_at desc);
create index if not exists messages_email_idx on site05.messages (lower(email));

-- ---------- Storage: stop public listing of files ----------
-- Public buckets serve files by URL without any SELECT policy, so only
-- admins need to list objects (the dashboard uses it to delete old files).
drop policy if exists "public read media [site05]" on storage.objects;
drop policy if exists "admin read media [site05]" on storage.objects;
drop policy if exists "admin read media [site05]" on storage.objects;
create policy "admin read media [site05]" on storage.objects for select to authenticated
  using (bucket_id = 'site05-media' and site05.is_admin());

-- ---------- Admins: users may only edit their name / avatar ----------
revoke update on site05.admins from anon, authenticated;
grant update (display_name, avatar_url) on site05.admins to authenticated;


-- >>> 0003_awards_sections.sql
-- =====================================================================
-- Awards + page-section settings (run after 0002_hardening.sql). Safe to re-run.
-- =====================================================================

-- ---------- Awards (optional section) ----------
create table if not exists site05.awards (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  organization text,
  year text,
  short_description text not null,
  image_url text not null,
  link_url text,
  active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_awards_updated on site05.awards;
create trigger trg_awards_updated before update on site05.awards
for each row execute function site05.set_updated_at();

alter table site05.awards enable row level security;

drop policy if exists "public read awards" on site05.awards;
drop policy if exists "admin insert awards" on site05.awards;
drop policy if exists "admin update awards" on site05.awards;
drop policy if exists "admin delete awards" on site05.awards;
drop policy if exists "public read awards" on site05.awards;
create policy "public read awards" on site05.awards for select using (active or site05.is_admin());
drop policy if exists "admin insert awards" on site05.awards;
create policy "admin insert awards" on site05.awards for insert to authenticated with check (site05.is_admin());
drop policy if exists "admin update awards" on site05.awards;
create policy "admin update awards" on site05.awards for update to authenticated using (site05.is_admin()) with check (site05.is_admin());
drop policy if exists "admin delete awards" on site05.awards;
create policy "admin delete awards" on site05.awards for delete to authenticated using (site05.is_admin());

-- ---------- Page sections: visibility + order ----------
alter table site05.site_settings
  add column if not exists sections jsonb not null default '[]'::jsonb;

-- ---------- Storage: allow the new "awards" upload folder ----------
drop policy if exists "admin upload media [site05]" on storage.objects;
drop policy if exists "admin upload media [site05]" on storage.objects;
create policy "admin upload media [site05]" on storage.objects for insert to authenticated
  with check (bucket_id = 'site05-media' and site05.is_admin()
    and (storage.foldername(name))[1] in ('profile', 'projects', 'services', 'testimonials', 'clients', 'awards', 'blog', 'documents', 'settings'));


-- >>> 0004_shop.sql
-- =====================================================================
-- Online shop (run after 0003_awards_sections.sql). Safe to re-run.
-- Categories, products, hero banners, FAQs, orders, newsletter and the
-- shop settings (delivery charges, payment numbers, offer banner …).
-- Orders are only created through site05.place_order(), which reads the real
-- prices from the database — visitors can never change a price or a total.
-- =====================================================================

-- ---------- Settings ----------
alter table site05.site_settings
  add column if not exists accent_color_2 text not null default '#c9a27a',
  add column if not exists announcement text not null default '',
  add column if not exists whatsapp_number text,
  add column if not exists delivery_inside int not null default 60 check (delivery_inside between 0 and 100000),
  add column if not exists delivery_outside int not null default 120 check (delivery_outside between 0 and 100000),
  add column if not exists free_delivery_min int not null default 0 check (free_delivery_min between 0 and 10000000),
  add column if not exists delivery_note text not null default '',
  add column if not exists order_prefix text not null default 'AH',
  add column if not exists cod_enabled boolean not null default true,
  add column if not exists bkash_number text,
  add column if not exists nagad_number text,
  add column if not exists rocket_number text,
  add column if not exists payment_qr_url text,
  add column if not exists payment_note text not null default '',
  add column if not exists promo_kicker text not null default '',
  add column if not exists promo_title text not null default '',
  add column if not exists promo_text text not null default '',
  add column if not exists promo_button text not null default '',
  add column if not exists promo_link text not null default '',
  add column if not exists promo_image_url text,
  add column if not exists promo_ends_at timestamptz,
  add column if not exists gallery_images jsonb not null default '[]'::jsonb,
  add column if not exists map_embed_url text,
  add column if not exists cursor_enabled boolean not null default true;

alter table site05.site_settings drop constraint if exists site_settings_accent_color_2_check;
alter table site05.site_settings add constraint site_settings_accent_color_2_check
  check (accent_color_2 ~* '^#([0-9a-f]{3}|[0-9a-f]{6})$');
alter table site05.site_settings drop constraint if exists site_settings_order_prefix_check;
alter table site05.site_settings add constraint site_settings_order_prefix_check
  check (order_prefix ~ '^[A-Z]{1,4}$');
alter table site05.site_settings drop constraint if exists site_settings_map_embed_url_check;
alter table site05.site_settings add constraint site_settings_map_embed_url_check
  check (
    map_embed_url is null
    or map_embed_url = ''
    or map_embed_url ~* '^https://(www\.google\.com/maps/embed|maps\.google\.com/maps|www\.openstreetmap\.org/export/embed\.html)'
  );

-- ---------- Profile: About page photo ----------
alter table site05.profile
  add column if not exists about_image_url text;

-- ---------- Categories ----------
create table if not exists site05.categories (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  description text not null default '',
  image_url text,
  active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------- Products ----------
create table if not exists site05.products (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  category_slug text references site05.categories (slug) on update cascade on delete set null,
  short_description text not null default '',
  description text not null default '',
  price int not null check (price between 0 and 10000000),
  sale_price int check (sale_price is null or (sale_price >= 0 and sale_price <= price)),
  images jsonb not null default '[]'::jsonb,
  colors jsonb not null default '[]'::jsonb,
  stock int not null default 0 check (stock between 0 and 1000000),
  sku text,
  badge text,
  featured boolean not null default false,
  is_new boolean not null default false,
  rating numeric(2, 1) not null default 5 check (rating between 0 and 5),
  review_count int not null default 0 check (review_count >= 0),
  status text not null default 'published' check (status in ('published', 'draft')),
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists products_category_idx on site05.products (category_slug);

-- ---------- Hero banners ----------
create table if not exists site05.banners (
  id uuid primary key default gen_random_uuid(),
  kicker text not null default '',
  title text not null,
  subtitle text not null default '',
  button_label text not null default 'Shop Now',
  button_link text not null default '/shop',
  image_url text not null,
  active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------- FAQs ----------
create table if not exists site05.faqs (
  id uuid primary key default gen_random_uuid(),
  question text not null,
  answer text not null,
  active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------- Orders ----------
create table if not exists site05.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique,
  customer_name text not null,
  phone text not null,
  email text,
  address text not null,
  city text not null default '',
  area text not null check (area in ('inside', 'outside')),
  note text not null default '',
  items jsonb not null,
  subtotal int not null,
  delivery_charge int not null,
  total int not null,
  payment_method text not null check (payment_method in ('cod', 'bkash', 'nagad', 'rocket', 'qr')),
  payment_sender text,
  payment_trx text,
  payment_status text not null default 'unpaid' check (payment_status in ('unpaid', 'paid', 'refunded')),
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'shipped', 'delivered', 'cancelled')),
  admin_note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists orders_created_at_idx on site05.orders (created_at desc);
create index if not exists orders_phone_idx on site05.orders (phone);

-- ---------- Newsletter ----------
create table if not exists site05.subscribers (
  id uuid primary key default gen_random_uuid(),
  email text not null unique check (email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$' and char_length(email) <= 120),
  created_at timestamptz not null default now()
);

-- ---------- updated_at triggers + RLS for the content tables ----------
do $$
declare t text;
begin
  foreach t in array array['categories', 'products', 'banners', 'faqs', 'orders'] loop
    execute format('drop trigger if exists trg_%1$s_updated on site05.%1$s', t);
    execute format('create trigger trg_%1$s_updated before update on site05.%1$s for each row execute function site05.set_updated_at()', t);
    execute format('alter table site05.%1$s enable row level security', t);
  end loop;
  foreach t in array array['categories', 'banners', 'faqs'] loop
    execute format('drop policy if exists "public read %1$s" on site05.%1$s', t);
    execute format('drop policy if exists "public read %1$s" on site05.%1$s', t);
    execute format('create policy "public read %1$s" on site05.%1$s for select using (active or site05.is_admin())', t);
  end loop;
  foreach t in array array['categories', 'products', 'banners', 'faqs'] loop
    execute format('drop policy if exists "admin insert %1$s" on site05.%1$s', t);
    execute format('drop policy if exists "admin update %1$s" on site05.%1$s', t);
    execute format('drop policy if exists "admin delete %1$s" on site05.%1$s', t);
    execute format('drop policy if exists "admin insert %1$s" on site05.%1$s', t);
    execute format('create policy "admin insert %1$s" on site05.%1$s for insert to authenticated with check (site05.is_admin())', t);
    execute format('drop policy if exists "admin update %1$s" on site05.%1$s', t);
    execute format('create policy "admin update %1$s" on site05.%1$s for update to authenticated using (site05.is_admin()) with check (site05.is_admin())', t);
    execute format('drop policy if exists "admin delete %1$s" on site05.%1$s', t);
    execute format('create policy "admin delete %1$s" on site05.%1$s for delete to authenticated using (site05.is_admin())', t);
  end loop;
end $$;

drop policy if exists "public read products" on site05.products;
drop policy if exists "public read products" on site05.products;
create policy "public read products" on site05.products for select using (status = 'published' or site05.is_admin());

-- Orders: only admins can read or change them. Nobody inserts directly (see place_order).
drop policy if exists "admin read orders" on site05.orders;
drop policy if exists "admin update orders" on site05.orders;
drop policy if exists "admin delete orders" on site05.orders;
drop policy if exists "admin read orders" on site05.orders;
create policy "admin read orders" on site05.orders for select to authenticated using (site05.is_admin());
drop policy if exists "admin update orders" on site05.orders;
create policy "admin update orders" on site05.orders for update to authenticated using (site05.is_admin()) with check (site05.is_admin());
drop policy if exists "admin delete orders" on site05.orders;
create policy "admin delete orders" on site05.orders for delete to authenticated using (site05.is_admin());

-- Newsletter: anyone can subscribe, only admins can see or remove.
alter table site05.subscribers enable row level security;
drop policy if exists "anyone can subscribe" on site05.subscribers;
drop policy if exists "admin read subscribers" on site05.subscribers;
drop policy if exists "admin delete subscribers" on site05.subscribers;
drop policy if exists "anyone can subscribe" on site05.subscribers;
create policy "anyone can subscribe" on site05.subscribers for insert to anon, authenticated with check (true);
drop policy if exists "admin read subscribers" on site05.subscribers;
create policy "admin read subscribers" on site05.subscribers for select to authenticated using (site05.is_admin());
drop policy if exists "admin delete subscribers" on site05.subscribers;
create policy "admin delete subscribers" on site05.subscribers for delete to authenticated using (site05.is_admin());

create or replace function site05.subscribers_guard()
returns trigger
language plpgsql security definer set search_path = site05
as $$
begin
  new.email := lower(trim(new.email));
  new.created_at := now();
  if (select count(*) from site05.subscribers where created_at > now() - interval '10 minutes') >= 50 then
    raise exception 'Too many sign-ups right now. Please try again later.' using errcode = 'P0001';
  end if;
  return new;
end $$;

drop trigger if exists trg_subscribers_guard on site05.subscribers;
create trigger trg_subscribers_guard before insert on site05.subscribers
for each row execute function site05.subscribers_guard();

-- ---------- Place an order (prices and totals are calculated here) ----------
create or replace function site05.place_order(payload jsonb)
returns jsonb
language plpgsql security definer set search_path = site05
as $$
declare
  s record;
  item jsonb;
  p record;
  v_qty int;
  v_unit int;
  v_color text;
  v_lines jsonb := '[]'::jsonb;
  v_subtotal int := 0;
  v_delivery int;
  v_method text := coalesce(payload->>'payment_method', '');
  v_area text := coalesce(payload->>'area', '');
  v_phone text := regexp_replace(coalesce(payload->>'phone', ''), '[\s-]', '', 'g');
  v_sender text := nullif(regexp_replace(coalesce(payload->>'payment_sender', ''), '[\s-]', '', 'g'), '');
  v_trx text := nullif(upper(trim(coalesce(payload->>'payment_trx', ''))), '');
  v_number text;
begin
  select * into s from site05.site_settings order by updated_at desc limit 1;
  if not found then
    raise exception 'The shop is not set up yet.' using errcode = 'P0001';
  end if;

  -- Customer details
  if char_length(trim(coalesce(payload->>'customer_name', ''))) not between 2 and 80 then
    raise exception 'Please enter your name.' using errcode = 'P0001';
  end if;
  if v_phone !~ '^(\+?88)?01[3-9][0-9]{8}$' then
    raise exception 'Please enter a valid mobile number.' using errcode = 'P0001';
  end if;
  if char_length(trim(coalesce(payload->>'address', ''))) not between 5 and 300 then
    raise exception 'Please enter your full address.' using errcode = 'P0001';
  end if;
  if v_area not in ('inside', 'outside') then
    raise exception 'Please choose a delivery area.' using errcode = 'P0001';
  end if;

  -- Payment method must be switched on in Settings
  if v_method = 'cod' and not s.cod_enabled
     or v_method = 'bkash' and coalesce(s.bkash_number, '') = ''
     or v_method = 'nagad' and coalesce(s.nagad_number, '') = ''
     or v_method = 'rocket' and coalesce(s.rocket_number, '') = ''
     or v_method = 'qr' and coalesce(s.payment_qr_url, '') = ''
     or v_method not in ('cod', 'bkash', 'nagad', 'rocket', 'qr') then
    raise exception 'Please choose a payment method.' using errcode = 'P0001';
  end if;
  if v_method <> 'cod' then
    if v_trx is null or v_trx !~ '^[A-Z0-9]{6,20}$' then
      raise exception 'Please enter the Transaction ID from your payment.' using errcode = 'P0001';
    end if;
    if v_method <> 'qr' and (v_sender is null or v_sender !~ '^(\+?88)?01[3-9][0-9]{8}$') then
      raise exception 'Please enter the number you paid from.' using errcode = 'P0001';
    end if;
  end if;

  -- Anti-spam
  if (select count(*) from site05.orders where created_at > now() - interval '10 minutes') >= 40 then
    raise exception 'Too many orders right now. Please try again in a few minutes.' using errcode = 'P0001';
  end if;
  if (select count(*) from site05.orders where phone = v_phone and created_at > now() - interval '1 hour') >= 5 then
    raise exception 'Too many orders from this number. Please contact us.' using errcode = 'P0001';
  end if;

  -- Items: real prices from the database, stock is checked and reserved
  if jsonb_typeof(payload->'items') <> 'array' or jsonb_array_length(payload->'items') not between 1 and 30 then
    raise exception 'Your cart is empty.' using errcode = 'P0001';
  end if;
  for item in select * from jsonb_array_elements(payload->'items') loop
    v_qty := coalesce((item->>'qty')::int, 0);
    if v_qty not between 1 and 20 then
      raise exception 'Invalid quantity.' using errcode = 'P0001';
    end if;
    select * into p from site05.products
      where id = (item->>'product_id')::uuid and status = 'published'
      for update;
    if not found then
      raise exception 'A product in your cart is no longer available.' using errcode = 'P0001';
    end if;
    if p.stock < v_qty then
      raise exception '% — only % left in stock.', p.name, p.stock using errcode = 'P0001';
    end if;
    v_color := left(nullif(trim(coalesce(item->>'color', '')), ''), 40);
    v_unit := coalesce(p.sale_price, p.price);
    v_subtotal := v_subtotal + v_unit * v_qty;
    v_lines := v_lines || jsonb_build_object(
      'product_id', p.id, 'name', p.name, 'slug', p.slug, 'image', p.images->>0,
      'price', v_unit, 'qty', v_qty, 'color', v_color
    );
    update site05.products set stock = stock - v_qty where id = p.id;
  end loop;

  v_delivery := case when v_area = 'inside' then s.delivery_inside else s.delivery_outside end;
  if s.free_delivery_min > 0 and v_subtotal >= s.free_delivery_min then
    v_delivery := 0;
  end if;

  loop
    v_number := coalesce(nullif(s.order_prefix, ''), 'AH') || to_char(now(), 'YYMMDD') || '-' || upper(substr(md5(random()::text), 1, 5));
    exit when not exists (select 1 from site05.orders where order_number = v_number);
  end loop;

  insert into site05.orders (order_number, customer_name, phone, email, address, city, area, note, items,
    subtotal, delivery_charge, total, payment_method, payment_sender, payment_trx)
  values (
    v_number,
    left(trim(payload->>'customer_name'), 80),
    v_phone,
    nullif(left(trim(coalesce(payload->>'email', '')), 120), ''),
    left(trim(payload->>'address'), 300),
    left(trim(coalesce(payload->>'city', '')), 60),
    v_area,
    left(trim(coalesce(payload->>'note', '')), 500),
    v_lines, v_subtotal, v_delivery, v_subtotal + v_delivery, v_method,
    case when v_method = 'cod' then null else v_sender end,
    case when v_method = 'cod' then null else v_trx end
  );

  return jsonb_build_object('order_number', v_number, 'total', v_subtotal + v_delivery);
end $$;

-- ---------- Track an order (needs the order number AND the phone number) ----------
create or replace function site05.track_order(p_number text, p_phone text)
returns jsonb
language sql stable security definer set search_path = site05
as $$
  select jsonb_build_object(
    'order_number', o.order_number,
    'status', o.status,
    'payment_status', o.payment_status,
    'payment_method', o.payment_method,
    'total', o.total,
    'items', jsonb_array_length(o.items),
    'created_at', o.created_at
  )
  from site05.orders o
  where o.order_number = upper(trim(p_number))
    and right(regexp_replace(o.phone, '\D', '', 'g'), 10) = right(regexp_replace(coalesce(p_phone, ''), '\D', '', 'g'), 10)
    and char_length(regexp_replace(coalesce(p_phone, ''), '\D', '', 'g')) >= 10
  limit 1
$$;

revoke all on function site05.place_order(jsonb) from public;
revoke all on function site05.track_order(text, text) from public;
grant execute on function site05.place_order(jsonb) to anon, authenticated;
grant execute on function site05.track_order(text, text) to anon, authenticated;

-- ---------- Storage: upload folders used by the shop ----------
drop policy if exists "admin upload media [site05]" on storage.objects;
drop policy if exists "admin upload media [site05]" on storage.objects;
create policy "admin upload media [site05]" on storage.objects for insert to authenticated
  with check (bucket_id = 'site05-media' and site05.is_admin()
    and (storage.foldername(name))[1] in ('profile', 'products', 'categories', 'banners', 'payments', 'gallery',
      'testimonials', 'blog', 'documents', 'settings'));


-- >>> seed.sql (demo content)
-- Demo content for Artificial Home (generated by scripts/generate-seed.ts).
-- Run AFTER all files in supabase/migrations (0001 – 0004).
-- It clears the shop content first. Orders, messages, subscribers and admins are untouched.
begin;
truncate site05.site_settings, site05.profile, site05.banners, site05.faqs, site05.testimonials, site05.blog_posts;
delete from site05.products;
delete from site05.categories;

insert into site05.site_settings (website_name, logo_url, accent_color, accent_color_2, default_theme, contact_email, public_phone, seo_title, seo_description, footer_text, hire_label, sections, announcement, whatsapp_number, delivery_inside, delivery_outside, free_delivery_min, delivery_note, order_prefix, cod_enabled, bkash_number, nagad_number, rocket_number, payment_qr_url, payment_note, promo_kicker, promo_title, promo_text, promo_button, promo_link, promo_image_url, promo_ends_at, gallery_images, map_embed_url, cursor_enabled) values
  ('Artificial Home', null, '#e0457b', '#c9956b', 'light', 'hello@artificialhome.demo', '+880 1712-345678', 'Artificial Home — Artificial Jewellery & Accessories in Bangladesh', 'Shop trendy artificial jewellery, bangles, earrings, necklaces, hair clips and beauty care. Cash on Delivery and bKash, Nagad, Rocket all over Bangladesh.', 'Trendy artificial jewellery, hair accessories and beauty care — made for every girl, delivered all over Bangladesh.', 'Shop Now', '[]'::jsonb, 'Free delivery on orders over ৳2,000 · Cash on Delivery all over Bangladesh', '8801712345678', 60, 120, 2000, 'Inside Dhaka: 1–2 days · Outside Dhaka: 2–4 days', 'AH', true, '01712-345678', '01812-345678', '01912-3456789', '/demo/payment-qr.svg', 'Use Send Money for the total amount, then enter the number you paid from and the Transaction ID.', 'Limited time offer', 'Festive Sale — Up to 40% Off', 'Bridal sets, jhumkas, bangles and more. New designs added every week.', 'Shop the Sale', '/shop?sale=1', '/demo/promo.svg', '2026-12-31T17:59:00.000Z', '["/demo/products/gold-jhumka-earrings-1.svg","/demo/products/pearl-hair-clip-set-1.svg","/demo/products/bridal-choker-necklace-1.svg","/demo/products/golden-kundan-churi-set-1.svg","/demo/products/rose-glow-face-cream-1.svg","/demo/products/rose-gold-charm-bracelet-1.svg"]'::jsonb, 'https://www.openstreetmap.org/export/embed.html?bbox=90.3866%2C23.7837%2C90.4266%2C23.8037&layer=mapnik&marker=23.7937%2C90.4066', true);

insert into site05.profile (full_name, professional_title, short_intro, bio, email, phone, location, profile_image_url, about_image_url, social_links) values
  ('Sumaiya Rahman', 'Founder, Artificial Home', 'From a small Facebook page to thousands of happy customers all over Bangladesh.', 'Artificial Home started in 2021 as a tiny Facebook page run from my bedroom in Dhaka. I loved jewellery but good designs were either too expensive or hard to find, so I started sourcing pieces I would wear myself.

Today we pack hundreds of orders every week — bangles, jhumkas, bridal sets, hair clips and gentle beauty care. Every piece is checked by hand before it leaves our studio, and we still read every message ourselves.

Thank you for being part of our story. We hope you find something that makes you smile.', 'hello@artificialhome.demo', '+880 1712-345678', 'Road 11, Banani, Dhaka', '/demo/avatar-owner.svg', '/demo/about-studio.svg', '[{"platform":"facebook","url":"https://facebook.com/"},{"platform":"instagram","url":"https://instagram.com/"},{"platform":"tiktok","url":"https://tiktok.com/"},{"platform":"youtube","url":"https://youtube.com/"},{"platform":"whatsapp","url":"https://wa.me/8801712345678"}]'::jsonb);

insert into site05.categories (name, slug, description, image_url, active, sort_order) values
  ('Bangles', 'bangles', 'Churi and kada for every outfit and occasion.', '/demo/cat-bangles.svg', true, 1),
  ('Earrings', 'earrings', 'Jhumka, chandbali, studs and pearl drops.', '/demo/cat-earrings.svg', true, 2),
  ('Necklaces', 'necklaces', 'Chokers, pendants and layered pearls.', '/demo/cat-necklaces.svg', true, 3),
  ('Jewellery Sets', 'jewellery-sets', 'Matching goina sets for weddings and parties.', '/demo/cat-jewellery-sets.svg', true, 4),
  ('Bracelets', 'bracelets', 'Charm, pearl and crystal bracelets.', '/demo/cat-bracelets.svg', true, 5),
  ('Hair Accessories', 'hair-accessories', 'Clips, claw clips, tikli and scrunchies.', '/demo/cat-hair-accessories.svg', true, 6),
  ('Beauty Care', 'beauty-care', 'Gentle creams, lipsticks and skin care.', '/demo/cat-beauty-care.svg', true, 7);

insert into site05.products (name, slug, category_slug, short_description, description, price, sale_price, images, colors, stock, sku, badge, featured, is_new, rating, review_count, status, sort_order) values
  ('Golden Kundan Churi Set', 'golden-kundan-churi-set', 'bangles', 'Set of 4 kundan bangles with ruby and emerald stones.', 'Set of 4 kundan bangles with ruby and emerald stones.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 1450, 1150, '["/demo/products/golden-kundan-churi-set-1.svg","/demo/products/golden-kundan-churi-set-2.svg"]'::jsonb, '[{"name":"Gold","hex":"#d4a24c"},{"name":"Rose Gold","hex":"#d9a08b"}]'::jsonb, 24, 'AH-001', 'Bestseller', true, false, 4.9, 128, 'published', 1),
  ('Pearl Glass Churi', 'pearl-glass-churi', 'bangles', 'Shiny glass churi with a soft pearl finish, set of 12.', 'Shiny glass churi with a soft pearl finish, set of 12.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 650, null, '["/demo/products/pearl-glass-churi-1.svg","/demo/products/pearl-glass-churi-2.svg"]'::jsonb, '[{"name":"Pearl White","hex":"#f4efe6"},{"name":"Pink","hex":"#f28ab2"}]'::jsonb, 40, 'AH-002', null, false, true, 4.7, 54, 'published', 2),
  ('Maroon Velvet Churi', 'maroon-velvet-churi', 'bangles', 'Velvet-wrapped bangles with golden stone work.', 'Velvet-wrapped bangles with golden stone work.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 890, 750, '["/demo/products/maroon-velvet-churi-1.svg","/demo/products/maroon-velvet-churi-2.svg"]'::jsonb, '[{"name":"Maroon","hex":"#7a1f35"},{"name":"Red","hex":"#c8203d"}]'::jsonb, 18, 'AH-003', 'Sale', false, false, 4.8, 61, 'published', 3),
  ('Oxidised Silver Kada', 'oxidised-silver-kada', 'bangles', 'Boho oxidised kada with a floral pattern.', 'Boho oxidised kada with a floral pattern.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 780, null, '["/demo/products/oxidised-silver-kada-1.svg","/demo/products/oxidised-silver-kada-2.svg"]'::jsonb, '[{"name":"Silver","hex":"#c0c4cc"}]'::jsonb, 15, 'AH-004', null, false, false, 4.6, 33, 'published', 4),
  ('Gold Jhumka Earrings', 'gold-jhumka-earrings', 'earrings', 'Classic bell jhumka with pearl drops.', 'Classic bell jhumka with pearl drops.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 850, 690, '["/demo/products/gold-jhumka-earrings-1.svg","/demo/products/gold-jhumka-earrings-2.svg"]'::jsonb, '[{"name":"Gold","hex":"#d4a24c"},{"name":"Rose Gold","hex":"#d9a08b"}]'::jsonb, 36, 'AH-005', 'Bestseller', true, false, 4.9, 212, 'published', 5),
  ('Pearl Drop Earrings', 'pearl-drop-earrings', 'earrings', 'Elegant single pearl drops for office and parties.', 'Elegant single pearl drops for office and parties.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 590, null, '["/demo/products/pearl-drop-earrings-1.svg","/demo/products/pearl-drop-earrings-2.svg"]'::jsonb, '[{"name":"Pearl White","hex":"#f4efe6"},{"name":"Gold","hex":"#d4a24c"}]'::jsonb, 30, 'AH-006', 'New', false, true, 4.8, 47, 'published', 6),
  ('Chandbali Earrings', 'chandbali-earrings', 'earrings', 'Half-moon chandbali with emerald stones.', 'Half-moon chandbali with emerald stones.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 1150, 950, '["/demo/products/chandbali-earrings-1.svg","/demo/products/chandbali-earrings-2.svg"]'::jsonb, '[{"name":"Gold","hex":"#d4a24c"},{"name":"Emerald","hex":"#1f7a5a"}]'::jsonb, 12, 'AH-007', 'Sale', true, false, 4.8, 88, 'published', 7),
  ('Tiny Stud Earring Set', 'tiny-stud-earring-set', 'earrings', 'Six pairs of tiny studs for everyday wear.', 'Six pairs of tiny studs for everyday wear.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 450, null, '["/demo/products/tiny-stud-earring-set-1.svg","/demo/products/tiny-stud-earring-set-2.svg"]'::jsonb, '[{"name":"Silver","hex":"#c0c4cc"},{"name":"Gold","hex":"#d4a24c"}]'::jsonb, 50, 'AH-008', null, false, false, 4.7, 76, 'published', 8),
  ('Bridal Choker Necklace', 'bridal-choker-necklace', 'necklaces', 'Kundan bridal choker with matching earrings.', 'Kundan bridal choker with matching earrings.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 2850, 2350, '["/demo/products/bridal-choker-necklace-1.svg","/demo/products/bridal-choker-necklace-2.svg"]'::jsonb, '[{"name":"Gold","hex":"#d4a24c"},{"name":"Red","hex":"#c8203d"}]'::jsonb, 9, 'AH-009', 'Bestseller', true, false, 5, 64, 'published', 9),
  ('Layered Pearl Necklace', 'layered-pearl-necklace', 'necklaces', 'Three layers of soft pearls on a golden chain.', 'Three layers of soft pearls on a golden chain.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 1350, null, '["/demo/products/layered-pearl-necklace-1.svg","/demo/products/layered-pearl-necklace-2.svg"]'::jsonb, '[{"name":"Pearl White","hex":"#f4efe6"}]'::jsonb, 20, 'AH-010', 'New', false, true, 4.8, 39, 'published', 10),
  ('Minimal Heart Pendant', 'minimal-heart-pendant', 'necklaces', 'Dainty heart pendant on a fine chain.', 'Dainty heart pendant on a fine chain.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 690, 590, '["/demo/products/minimal-heart-pendant-1.svg","/demo/products/minimal-heart-pendant-2.svg"]'::jsonb, '[{"name":"Rose Gold","hex":"#d9a08b"},{"name":"Gold","hex":"#d4a24c"},{"name":"Silver","hex":"#c0c4cc"}]'::jsonb, 45, 'AH-011', null, false, false, 4.7, 102, 'published', 11),
  ('Temple Coin Necklace', 'temple-coin-necklace', 'necklaces', 'Traditional coin necklace with antique finish.', 'Traditional coin necklace with antique finish.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 1950, null, '["/demo/products/temple-coin-necklace-1.svg","/demo/products/temple-coin-necklace-2.svg"]'::jsonb, '[{"name":"Gold","hex":"#d4a24c"}]'::jsonb, 8, 'AH-012', null, false, false, 4.8, 29, 'published', 12),
  ('Bridal Goina Set', 'bridal-goina-set', 'jewellery-sets', 'Necklace, jhumka and tikli — the full bridal look.', 'Necklace, jhumka and tikli — the full bridal look.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 4950, 3990, '["/demo/products/bridal-goina-set-1.svg","/demo/products/bridal-goina-set-2.svg"]'::jsonb, '[{"name":"Gold","hex":"#d4a24c"},{"name":"Maroon","hex":"#7a1f35"}]'::jsonb, 6, 'AH-013', 'Bestseller', true, false, 5, 41, 'published', 13),
  ('Party Wear Necklace Set', 'party-wear-necklace-set', 'jewellery-sets', 'Crystal necklace with matching studs.', 'Crystal necklace with matching studs.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 2450, 1990, '["/demo/products/party-wear-necklace-set-1.svg","/demo/products/party-wear-necklace-set-2.svg"]'::jsonb, '[{"name":"Silver","hex":"#c0c4cc"},{"name":"Lilac","hex":"#b99ad8"}]'::jsonb, 14, 'AH-014', 'New', true, true, 4.8, 36, 'published', 14),
  ('Everyday Pearl Set', 'everyday-pearl-set', 'jewellery-sets', 'Light pearl necklace and earrings for daily wear.', 'Light pearl necklace and earrings for daily wear.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 1690, null, '["/demo/products/everyday-pearl-set-1.svg","/demo/products/everyday-pearl-set-2.svg"]'::jsonb, '[{"name":"Pearl White","hex":"#f4efe6"},{"name":"Rose Gold","hex":"#d9a08b"}]'::jsonb, 22, 'AH-015', null, false, false, 4.7, 45, 'published', 15),
  ('Rose Gold Charm Bracelet', 'rose-gold-charm-bracelet', 'bracelets', 'Charm bracelet with heart, star and moon.', 'Charm bracelet with heart, star and moon.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 950, 790, '["/demo/products/rose-gold-charm-bracelet-1.svg","/demo/products/rose-gold-charm-bracelet-2.svg"]'::jsonb, '[{"name":"Rose Gold","hex":"#d9a08b"},{"name":"Gold","hex":"#d4a24c"}]'::jsonb, 28, 'AH-016', 'Sale', true, false, 4.8, 73, 'published', 16),
  ('Pearl Beaded Bracelet', 'pearl-beaded-bracelet', 'bracelets', 'Stretchable pearl bracelet, one size fits all.', 'Stretchable pearl bracelet, one size fits all.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 550, null, '["/demo/products/pearl-beaded-bracelet-1.svg","/demo/products/pearl-beaded-bracelet-2.svg"]'::jsonb, '[{"name":"Pearl White","hex":"#f4efe6"},{"name":"Pink","hex":"#f28ab2"}]'::jsonb, 35, 'AH-017', 'New', false, true, 4.7, 38, 'published', 17),
  ('Crystal Tennis Bracelet', 'crystal-tennis-bracelet', 'bracelets', 'Sparkling crystal line bracelet for evenings.', 'Sparkling crystal line bracelet for evenings.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 1250, 990, '["/demo/products/crystal-tennis-bracelet-1.svg","/demo/products/crystal-tennis-bracelet-2.svg"]'::jsonb, '[{"name":"Silver","hex":"#c0c4cc"},{"name":"Rose Gold","hex":"#d9a08b"}]'::jsonb, 16, 'AH-018', null, false, false, 4.8, 52, 'published', 18),
  ('Pearl Hair Clip Set', 'pearl-hair-clip-set', 'hair-accessories', 'Set of 6 pearl hair clips in different sizes.', 'Set of 6 pearl hair clips in different sizes.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 390, 320, '["/demo/products/pearl-hair-clip-set-1.svg","/demo/products/pearl-hair-clip-set-2.svg"]'::jsonb, '[{"name":"Pearl White","hex":"#f4efe6"},{"name":"Gold","hex":"#d4a24c"}]'::jsonb, 60, 'AH-019', 'Bestseller', true, true, 4.9, 184, 'published', 19),
  ('Butterfly Claw Clips', 'butterfly-claw-clips', 'hair-accessories', 'Pack of 3 matte butterfly claw clips.', 'Pack of 3 matte butterfly claw clips.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 350, null, '["/demo/products/butterfly-claw-clips-1.svg","/demo/products/butterfly-claw-clips-2.svg"]'::jsonb, '[{"name":"Pink","hex":"#f28ab2"},{"name":"Lilac","hex":"#b99ad8"},{"name":"Black","hex":"#222222"}]'::jsonb, 55, 'AH-020', 'New', false, true, 4.7, 97, 'published', 20),
  ('Floral Bridal Tikli', 'floral-bridal-tikli', 'hair-accessories', 'Maang tikka with a floral kundan centre.', 'Maang tikka with a floral kundan centre.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 750, 650, '["/demo/products/floral-bridal-tikli-1.svg","/demo/products/floral-bridal-tikli-2.svg"]'::jsonb, '[{"name":"Gold","hex":"#d4a24c"},{"name":"Red","hex":"#c8203d"}]'::jsonb, 20, 'AH-021', null, false, false, 4.8, 44, 'published', 21),
  ('Satin Scrunchie Pack', 'satin-scrunchie-pack', 'hair-accessories', 'Pack of 5 soft satin scrunchies.', 'Pack of 5 soft satin scrunchies.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 290, null, '["/demo/products/satin-scrunchie-pack-1.svg","/demo/products/satin-scrunchie-pack-2.svg"]'::jsonb, '[{"name":"Pink","hex":"#f28ab2"},{"name":"Maroon","hex":"#7a1f35"},{"name":"Black","hex":"#222222"}]'::jsonb, 80, 'AH-022', null, false, false, 4.6, 58, 'published', 22),
  ('Rose Glow Face Cream', 'rose-glow-face-cream', 'beauty-care', 'Light day cream with rose water and vitamin E.', 'Light day cream with rose water and vitamin E.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 650, 550, '["/demo/products/rose-glow-face-cream-1.svg","/demo/products/rose-glow-face-cream-2.svg"]'::jsonb, '[]'::jsonb, 40, 'AH-023', 'Bestseller', true, false, 4.8, 156, 'published', 23),
  ('Velvet Matte Lipstick', 'velvet-matte-lipstick', 'beauty-care', 'Long-lasting matte lipstick, soft on the lips.', 'Long-lasting matte lipstick, soft on the lips.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 450, null, '["/demo/products/velvet-matte-lipstick-1.svg","/demo/products/velvet-matte-lipstick-2.svg"]'::jsonb, '[{"name":"Red","hex":"#c8203d"},{"name":"Nude","hex":"#c98f7a"},{"name":"Pink","hex":"#f28ab2"},{"name":"Maroon","hex":"#7a1f35"}]'::jsonb, 70, 'AH-024', 'New', false, true, 4.7, 91, 'published', 24),
  ('Aloe Vera Night Gel', 'aloe-vera-night-gel', 'beauty-care', 'Soothing aloe night gel for all skin types.', 'Soothing aloe night gel for all skin types.

Every piece is checked by hand before it is packed. The plating is skin-friendly and lightweight, so it is comfortable to wear for long events.

## Care tips
- Keep away from water, perfume and lotion
- Wipe gently with a soft, dry cloth after wearing
- Store in the zip pouch that comes with your order', 390, null, '["/demo/products/aloe-vera-night-gel-1.svg","/demo/products/aloe-vera-night-gel-2.svg"]'::jsonb, '[]'::jsonb, 45, 'AH-025', null, false, false, 4.6, 67, 'published', 25);

insert into site05.banners (kicker, title, subtitle, button_label, button_link, image_url, active, sort_order) values
  ('New Bridal Collection', 'Shine Brighter on Your Special Day', 'Handpicked kundan sets, jhumkas and tikli — made to make every moment golden.', 'Shop Bridal', '/shop/jewellery-sets', '/demo/banner-bridal.svg', true, 1),
  ('Festive Sale · Up to 40% Off', 'Jhumkas & Bangles You''ll Love', 'Trending designs for Eid, weddings and every party this season.', 'Shop the Sale', '/shop?sale=1', '/demo/banner-sale.svg', true, 2),
  ('Everyday Pearls', 'Little Details, Big Smiles', 'Pearl clips, dainty chains and studs for college, office and brunch.', 'Explore New In', '/shop?new=1', '/demo/banner-pearls.svg', true, 3);

insert into site05.testimonials (name, role, company, project_title, quote, avatar_url, rating, active, sort_order) values
  ('Nusrat Jahan', 'Dhaka', null, 'Bridal Goina Set', 'I wore the bridal set on my holud and everyone asked where I got it! It looks exactly like the pictures and the packaging was so pretty.', '/demo/avatar-1.svg', 5, true, 1),
  ('Tasnim Akter', 'Chattogram', null, 'Gold Jhumka Earrings', 'Delivery to Chattogram took just 2 days. The jhumkas are light and don''t hurt my ears even after a full day.', '/demo/avatar-2.svg', 5, true, 2),
  ('Sadia Islam', 'Sylhet', null, 'Pearl Hair Clip Set', 'Ordered with bKash and they confirmed on WhatsApp within minutes. The pearl clips are my new favourite for college.', '/demo/avatar-3.svg', 5, true, 3),
  ('Farzana Rahman', 'Rajshahi', null, 'Rose Glow Face Cream', 'The rose cream is so light and smells lovely. My skin feels soft all day. Already ordered my second jar!', '/demo/avatar-4.svg', 4, true, 4);

insert into site05.faqs (question, answer, active, sort_order) values
  ('How do I place an order?', 'Add products to your cart, go to Checkout, fill in your name, phone and address, choose a payment method and press Place Order. You can also order on WhatsApp.', true, 1),
  ('What are the delivery charges?', 'Inside Dhaka ৳60 and outside Dhaka ৳120. Orders over ৳2,000 get free delivery.', true, 2),
  ('How long does delivery take?', 'Inside Dhaka 1–2 working days, outside Dhaka 2–4 working days. We call you before sending the parcel.', true, 3),
  ('Which payment methods do you accept?', 'Cash on Delivery all over Bangladesh, plus bKash, Nagad, Rocket and Bangla QR. For mobile payments, send the total and enter your Transaction ID at checkout.', true, 4),
  ('Can I return or exchange a product?', 'Yes. If a product arrives damaged or different from the picture, tell us within 3 days with a photo and we will exchange it for free.', true, 5),
  ('Is the jewellery safe for sensitive skin?', 'Our pieces use skin-friendly, nickel-free plating. Keep them away from water and perfume to keep the shine for longer.', true, 6);

insert into site05.blog_posts (title, slug, excerpt, content, cover_image_url, category, read_time, published_at, status) values
  ('How to Keep Your Artificial Jewellery Shining for Years', 'care-for-artificial-jewellery', 'Five simple habits that keep your favourite pieces looking brand new.', 'Artificial jewellery can last for years with a little care. These habits make the biggest difference.

## 1. Put it on last
Wear your jewellery after perfume, lotion and hairspray, not before.

## 2. Keep it dry
Take it off before a shower, a swim or washing your hands.

## 3. Wipe after wearing
A soft, dry cloth removes sweat and oil that make plating dull.

## 4. Store pieces separately
Use the zip pouch or a soft box so pieces don''t scratch each other.

## 5. Add silica gel
A small silica packet in your jewellery box keeps moisture away.', '/demo/blog-care.svg', 'Jewellery Care', '3 min read', '2026-09-20', 'published'),
  ('5 Jewellery Trends Every Girl Will Love This Season', 'jewellery-trends-this-season', 'From oversized jhumkas to pearl hair clips — here is what everyone is wearing.', 'This season is all about mixing traditional and modern.

## Oversized jhumkas
Big bells with pearl drops look amazing with both saree and kurti.

## Pearl everything
Pearl clips, pearl bracelets and layered pearl necklaces are everywhere.

## Stacked bangles
Mix velvet, glass and metal churi in two or three colours.

## Dainty pendants
A tiny heart or initial pendant is perfect for college and office.

## Claw clips
Matte butterfly claw clips are the easiest way to look put-together in seconds.', '/demo/blog-trends.svg', 'Style Guide', '4 min read', '2026-09-05', 'published'),
  ('Choosing Earrings for Your Face Shape', 'earrings-for-your-face-shape', 'A quick guide to finding earrings that flatter you the most.', 'The right earrings can brighten your whole look. Here is a simple guide.

## Round face
Long drops and chandbalis add length.

## Oval face
Lucky you — almost everything works, from studs to big jhumkas.

## Square face
Round hoops and soft pearl drops soften strong angles.

## Heart face
Earrings that are wider at the bottom, like jhumkas, balance a narrow chin.', '/demo/blog-earrings.svg', 'Style Guide', '3 min read', '2026-08-18', 'published');

commit;

-- ------------------------------------------------------------------
-- Make your dashboard owner (run once, after creating the user in
-- Supabase -> Authentication -> Users). Replace the email below.
-- ------------------------------------------------------------------
-- insert into site05.admins (user_id, display_name)
-- select id, 'Shop Owner' from auth.users where email = 'owner@example.com'
-- on conflict (user_id) do update set active = true;


-- Tables that already existed before a re-run keep their grants; make sure they are set.
grant select, insert, update, delete on all tables in schema site05 to anon, authenticated, service_role;
revoke update on site05.admins from anon, authenticated;
grant update (display_name, avatar_url) on site05.admins to authenticated;

-- Make the dashboard owner for THIS website (create the user first in Authentication → Users):
-- insert into site05.admins (user_id, display_name)
-- select id, 'Owner Name' from auth.users where email = 'owner@example.com'
-- on conflict (user_id) do update set active = true;
