// Generates supabase/seed.sql from src/data/demo.ts so demo content stays in one place.
// Run: npm run seed:generate
import { writeFileSync } from "node:fs";
import * as demo from "../src/data/demo.ts";

type Row = Record<string, unknown>;

function lit(v: unknown): string {
  if (v === null || v === undefined) return "null";
  if (typeof v === "boolean") return v ? "true" : "false";
  if (typeof v === "number") return String(v);
  if (Array.isArray(v) && v.every((x) => typeof x === "string")) {
    return `array[${v.map((x) => lit(x)).join(", ")}]::text[]`;
  }
  if (typeof v === "object") return `${lit(JSON.stringify(v))}::jsonb`;
  return `'${String(v).replace(/'/g, "''")}'`;
}

const json = (v: unknown) => ({ __raw: `${lit(JSON.stringify(v))}::jsonb` });

function insert(table: string, rows: Row[], omit: string[] = ["id"]) {
  if (!rows.length) return "";
  const cols = Object.keys(rows[0]).filter((c) => !omit.includes(c));
  const values = rows
    .map(
      (r) =>
        `  (${cols
          .map((c) => {
            const v = r[c] as any;
            return v && typeof v === "object" && "__raw" in v ? v.__raw : lit(v);
          })
          .join(", ")})`
    )
    .join(",\n");
  return `insert into public.${table} (${cols.join(", ")}) values\n${values};\n\n`;
}

let sql = `-- Demo content for Artificial Home (generated by scripts/generate-seed.ts).
-- Run AFTER all files in supabase/migrations (0001 – 0004).
-- It clears the shop content first. Orders, messages, subscribers and admins are untouched.
begin;
truncate public.site_settings, public.profile, public.banners, public.faqs, public.testimonials, public.blog_posts;
delete from public.products;
delete from public.categories;

`;
sql += insert("site_settings", [{ ...demo.demoSettings, sections: json(demo.demoSettings.sections), gallery_images: json(demo.demoSettings.gallery_images) }]);
sql += insert("profile", [{ ...demo.demoProfile, social_links: json(demo.demoProfile.social_links) }]);
sql += insert("categories", demo.demoCategories as Row[]);
sql += insert("products", demo.demoProducts.map((p) => ({ ...p, images: json(p.images), colors: json(p.colors) })));
sql += insert("banners", demo.demoBanners as Row[]);
sql += insert("testimonials", demo.demoReviews as Row[]);
sql += insert("faqs", demo.demoFaqs as Row[]);
sql += insert("blog_posts", demo.demoPosts as Row[]);
sql += `commit;

-- ------------------------------------------------------------------
-- Make your dashboard owner (run once, after creating the user in
-- Supabase -> Authentication -> Users). Replace the email below.
-- ------------------------------------------------------------------
-- insert into public.admins (user_id, display_name)
-- select id, 'Shop Owner' from auth.users where email = 'owner@example.com'
-- on conflict (user_id) do update set active = true;
`;

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), sql);
console.log("supabase/seed.sql written");
